# Part One

Question 3

In [1]:
import numpy as np
from scipy import stats as st

In [2]:
arr = np.random.uniform(0,100,[100,1])

In [3]:
arr = arr.astype(int)

In [4]:
meanvalue = np.mean(arr)
print(meanvalue)

53.85


In [5]:
modevalue = st.mode(arr)
print (modevalue)

ModeResult(mode=array([[24]]), count=array([[3]]))


In [6]:
var = np.var(arr)
print(var)

843.1275


In [7]:
iqr = st.iqr(arr)
print(iqr)

55.0


# Part 2

### Question 1

In [8]:
class array1():
    def __init__(self):
        self.array = []
    def get_array(self,length):
        for _ in range(length):
            element=int(input())
            self.array.append(element)
        self.array.sort()
        return self.array

In [9]:
mynums = array1()

In [10]:
sorted = mynums.get_array(length=2)


3
1


In [11]:
print(sorted)

[1, 3]


### Question 2

#### Using basic python

In [12]:
matrix = [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12],
          [13,14,15,16]]

In [13]:
print(len(matrix))

4


In [14]:
for _ in range(len(matrix)):
    print(matrix[_][_])

1
6
11
16


In [15]:
temp = 0
for _ in range(len(matrix)):
    temp+= matrix[_][_]
print(temp)

34


In [16]:
for _ in range(len(matrix)):
    print(max(matrix[_]),min(matrix[_])) 
    

4 1
8 5
12 9
16 13


#### Using numpy array functions

In [17]:
mat = np.array(matrix)
print(np.diagonal(mat))

[ 1  6 11 16]


In [18]:
print(np.trace(mat))

34


In [19]:
for _ in range(len(mat)):
    print(max(mat[_]),min(mat[_]))

4 1
8 5
12 9
16 13


In [20]:
matA = np.random.rand(4,4)
print(matA)

[[0.39228397 0.76666585 0.79390727 0.28988453]
 [0.96468159 0.10135732 0.14465386 0.03232322]
 [0.04365785 0.09381241 0.41580378 0.04356559]
 [0.07298805 0.58366126 0.8386657  0.56727443]]


In [21]:
matB = np.random.uniform(0,1,[4,4])
print(matB)

[[0.96505519 0.82870364 0.41106942 0.71877205]
 [0.53947891 0.63322341 0.08906715 0.88346192]
 [0.67818745 0.20722128 0.38837401 0.12194974]
 [0.1564293  0.73373682 0.81446629 0.79093283]]


In [22]:
np.dot(matA,matB)

array([[1.37594011, 1.18777135, 0.77397482, 1.28537881],
       [1.08880985, 0.91730907, 0.48808469, 0.82613749],
       [0.3815499 , 0.2137127 , 0.2232721 , 0.19942435],
       [1.04282134, 1.02009295, 0.86973006, 1.1190553 ]])

In [23]:
np.dot(matB,matA)

array([[1.24841901, 1.28195285, 1.6597732 , 0.73219043],
       [0.89085854, 1.00177998, 1.2978581 , 0.68190002],
       [0.49180106, 0.64855819, 0.83215575, 0.28939282],
       [0.86247361, 0.7323425 , 1.23231462, 0.55322184]])

### Question 3

In [24]:
import pandas as pd

In [25]:
df = pd.read_csv("Data - STOCK_US_XNYS_CSV.csv")

In [26]:
df

Date   Open   High    Low  Close   Volume
0    05/05/2023  26.93  27.71  26.59  27.59  146,854
1    05/04/2023  29.17  29.17  26.12  26.74  187,882
2    05/03/2023  29.00  29.36  27.83  28.09  138,729
3    05/02/2023  29.39  29.39  28.47  28.96  132,896
4    05/01/2023  28.80  29.74  28.80  29.69   58,964
..          ...    ...    ...    ...    ...      ...
247  05/11/2022  39.59  40.70  38.90  38.99  212,540
248  05/10/2022  40.23  40.97  39.15  39.29  263,363
249  05/09/2022  40.67  40.80  39.50  40.07  171,351
250  05/06/2022  41.33  41.53  40.22  41.30  112,366
251  05/05/2022  42.81  42.95  40.88  41.49   85,554

[252 rows x 6 columns]

In [27]:
df.describe()

Open        High         Low       Close
count  252.000000  252.000000  252.000000  252.000000
mean    32.948730   33.469008   32.348056   32.905437
std      5.298971    5.356194    5.267418    5.333756
min     23.580000   24.050000   22.710000   23.400000
25%     28.937500   29.207500   28.500000   28.855000
50%     32.360000   32.895000   31.770000   32.400000
75%     38.007500   38.847500   37.195000   37.942500
max     44.060000   44.520000   43.220000   44.050000

In [28]:
df.Date = pd.to_datetime(df.Date)
df
df.groupby([df.Date.dt.year,df.Date.dt.month])['Close'].mean()


Date  Date
2022  5       39.631111
      6       39.171429
      7       40.386000
      8       38.048696
      9       33.766667
      10      30.941429
      11      24.519524
      12      26.083810
2023  1       30.363000
      2       32.954211
      3       31.898696
      4       28.615789
      5       28.214000
Name: Close, dtype: float64

# Part 3

In [29]:
average = df['Close'].rolling(30).mean()

In [30]:
average

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...    
247    39.220000
248    39.277667
249    39.384000
250    39.502667
251    39.697667
Name: Close, Length: 252, dtype: float64

In [31]:
df['MovAvg'] = average

In [32]:
df

Date   Open   High    Low  Close   Volume     MovAvg
0   2023-05-05  26.93  27.71  26.59  27.59  146,854        NaN
1   2023-05-04  29.17  29.17  26.12  26.74  187,882        NaN
2   2023-05-03  29.00  29.36  27.83  28.09  138,729        NaN
3   2023-05-02  29.39  29.39  28.47  28.96  132,896        NaN
4   2023-05-01  28.80  29.74  28.80  29.69   58,964        NaN
..         ...    ...    ...    ...    ...      ...        ...
247 2022-05-11  39.59  40.70  38.90  38.99  212,540  39.220000
248 2022-05-10  40.23  40.97  39.15  39.29  263,363  39.277667
249 2022-05-09  40.67  40.80  39.50  40.07  171,351  39.384000
250 2022-05-06  41.33  41.53  40.22  41.30  112,366  39.502667
251 2022-05-05  42.81  42.95  40.88  41.49   85,554  39.697667

[252 rows x 7 columns]

print the dates and closing
prices for the days on which the rolling average exceeded the closing price by more
than 5%, sorted by date in ascending order.

In [33]:
lis = []
for i,row in df.iterrows():
    if(row['MovAvg']>1.05*row['Close']):
        lis.append([row['Date'],row['Close']])
print(lis)

[[Timestamp('2023-02-09 00:00:00'), 30.68], [Timestamp('2023-01-30 00:00:00'), 31.1], [Timestamp('2023-01-27 00:00:00'), 31.29], [Timestamp('2023-01-25 00:00:00'), 30.85], [Timestamp('2023-01-24 00:00:00'), 30.85], [Timestamp('2023-01-23 00:00:00'), 30.65], [Timestamp('2023-01-20 00:00:00'), 30.57], [Timestamp('2023-01-19 00:00:00'), 30.37], [Timestamp('2023-01-18 00:00:00'), 30.11], [Timestamp('2023-01-17 00:00:00'), 30.56], [Timestamp('2023-01-13 00:00:00'), 30.27], [Timestamp('2023-01-12 00:00:00'), 30.21], [Timestamp('2023-01-09 00:00:00'), 29.27], [Timestamp('2023-01-05 00:00:00'), 28.94], [Timestamp('2023-01-04 00:00:00'), 29.13], [Timestamp('2023-01-03 00:00:00'), 28.56], [Timestamp('2022-12-30 00:00:00'), 27.54], [Timestamp('2022-12-29 00:00:00'), 27.63], [Timestamp('2022-12-28 00:00:00'), 27.2], [Timestamp('2022-12-27 00:00:00'), 27.14], [Timestamp('2022-12-23 00:00:00'), 27.47], [Timestamp('2022-12-22 00:00:00'), 27.3], [Timestamp('2022-12-21 00:00:00'), 27.17], [Timestamp('2